apiVersion: v1
kind: Service
metadata:
# the name of the service is used in the app which refer as the host name
  name: db 
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: demo-voting-app
  ports:
    - port: 5432
      targetPort: 5432