apiVersion: v1
kind: Service
metadata:
# the name of the service is used in the app which refer as the host name
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
    - port: 6379
      targetPort: 6379